"""Commit migration

Revision ID: 0658bb2212df
Revises: 3fecf80ff862
Create Date: 2023-08-24 10:56:57.101044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0658bb2212df'
down_revision: Union[str, None] = '3fecf80ff862'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_blog', sa.Column('blog_id', sa.Integer(), nullable=False))
    op.add_column('user_blog', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('user_blog_blog_forei_fkey', 'user_blog', type_='foreignkey')
    op.drop_constraint('user_blog_user_forei_fkey', 'user_blog', type_='foreignkey')
    op.create_foreign_key(None, 'user_blog', 'blog', ['blog_id'], ['id'])
    op.create_foreign_key(None, 'user_blog', 'user', ['user_id'], ['id'])
    op.drop_column('user_blog', 'user_forei')
    op.drop_column('user_blog', 'blog_forei')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_blog', sa.Column('blog_forei', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('user_blog', sa.Column('user_forei', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_blog', type_='foreignkey')
    op.drop_constraint(None, 'user_blog', type_='foreignkey')
    op.create_foreign_key('user_blog_user_forei_fkey', 'user_blog', 'user', ['user_forei'], ['id'])
    op.create_foreign_key('user_blog_blog_forei_fkey', 'user_blog', 'blog', ['blog_forei'], ['id'])
    op.drop_column('user_blog', 'user_id')
    op.drop_column('user_blog', 'blog_id')
    # ### end Alembic commands ###
