"""Commit migration

Revision ID: 46fa6e3a2b42
Revises: 5a84a0c06e4c
Create Date: 2023-08-29 11:41:40.985210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46fa6e3a2b42'
down_revision: Union[str, None] = '5a84a0c06e4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
