"""Commit migration

Revision ID: 4cd08faf0b84
Revises: 0658bb2212df
Create Date: 2023-08-24 11:07:17.372571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cd08faf0b84'
down_revision: Union[str, None] = '0658bb2212df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_model_test_email', table_name='model_test')
    op.drop_index('ix_model_test_id', table_name='model_test')
    op.drop_table('model_test')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_test',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='model_test_pkey')
    )
    op.create_index('ix_model_test_id', 'model_test', ['id'], unique=False)
    op.create_index('ix_model_test_email', 'model_test', ['email'], unique=False)
    # ### end Alembic commands ###
