"""Commit migration

Revision ID: d2a5dda8a86b
Revises: 5d67d2322604
Create Date: 2023-08-24 10:26:42.803646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2a5dda8a86b'
down_revision: Union[str, None] = '5d67d2322604'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('account')
    op.add_column('user', sa.Column('blogs_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'blog', ['blogs_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'blogs_id')
    op.create_table('account',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='account_pkey')
    )
    # ### end Alembic commands ###
